version: "1.0"

services:
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    restart: always
    networks:
      - crudapp-network

  books-api:
    image: books-api:v1
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - mongodb
    networks:
      - crudapp-network

networks:
  crudapp-network:
    external:
      name: crudapp_default
