version: "1.0"

services:
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    restart: always

  books-api:
    image: books-api:v1
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - mongodb

